version: "3"
services:
  freqtrade:
    image: freqtradeorg/freqtrade:latest
    volumes:
      - user_data:/freqtrade/user_data
      - user_data_strategies:/freqtrade/user_data/strategies
    ports:
      - "8080:8080"
    command: trade --config /freqtrade/user_data/config.json --strategy SMAOffsetProtectOptV1

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: freqtrade
      POSTGRES_USER: freqtrade
      POSTGRES_PASSWORD: freqtrade
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data

volumes:
  user_data:
  user_data_strategies:
  pg_data:
  redis_data:
